spring.application.name=elearning
spring.mongodb.uri=${MONGODB_URI}
app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-exp-minutes=15
app.jwt.refresh-token-exp-days=7

app.upload.avatar-dir=uploads/avatars
app.base-url=http://localhost:8080


